from django.shortcuts import render, redirect
from django.http import JsonResponse


# Create your views here.


def card_view(request):
    # card = models.Card()
    # card.name = "CQUAD4"
    # card.id = 12
    # card.count = 987
    card_json = {
        'CQUAD4': [{'name': 'CQUAD4', 'id': '1', 'property': '1'}, {'name': 'CQUAD4', 'id': '2', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '3', 'property': '1'}, {'name': 'CQUAD4', 'id': '6', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '9', 'property': '1'}, {'name': 'CQUAD4', 'id': '10', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '11', 'property': '1'}, {'name': 'CQUAD4', 'id': '12', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '13', 'property': '1'}, {'name': 'CQUAD4', 'id': '14', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '17', 'property': '1'}, {'name': 'CQUAD4', 'id': '20', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '21', 'property': '1'}, {'name': 'CQUAD4', 'id': '22', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '23', 'property': '1'}, {'name': 'CQUAD4', 'id': '24', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '25', 'property': '1'}, {'name': 'CQUAD4', 'id': '28', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '31', 'property': '1'}, {'name': 'CQUAD4', 'id': '32', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '33', 'property': '1'}, {'name': 'CQUAD4', 'id': '34', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '35', 'property': '1'}, {'name': 'CQUAD4', 'id': '36', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '39', 'property': '1'}, {'name': 'CQUAD4', 'id': '42', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '43', 'property': '1'}, {'name': 'CQUAD4', 'id': '44', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '45', 'property': '1'}, {'name': 'CQUAD4', 'id': '46', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '47', 'property': '1'}, {'name': 'CQUAD4', 'id': '50', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '53', 'property': '1'}, {'name': 'CQUAD4', 'id': '54', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '55', 'property': '1'}, {'name': 'CQUAD4', 'id': '56', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '57', 'property': '1'}, {'name': 'CQUAD4', 'id': '58', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '61', 'property': '1'}, {'name': 'CQUAD4', 'id': '64', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '65', 'property': '1'}, {'name': 'CQUAD4', 'id': '66', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '67', 'property': '1'}, {'name': 'CQUAD4', 'id': '68', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '69', 'property': '1'}, {'name': 'CQUAD4', 'id': '72', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '75', 'property': '1'}, {'name': 'CQUAD4', 'id': '76', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '77', 'property': '1'}, {'name': 'CQUAD4', 'id': '78', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '79', 'property': '1'}, {'name': 'CQUAD4', 'id': '80', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '83', 'property': '1'}, {'name': 'CQUAD4', 'id': '86', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '87', 'property': '1'}, {'name': 'CQUAD4', 'id': '88', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '89', 'property': '1'}, {'name': 'CQUAD4', 'id': '90', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '91', 'property': '1'}, {'name': 'CQUAD4', 'id': '94', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '97', 'property': '1'}, {'name': 'CQUAD4', 'id': '98', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '99', 'property': '1'}, {'name': 'CQUAD4', 'id': '100', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '101', 'property': '1'}, {'name': 'CQUAD4', 'id': '102', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '105', 'property': '1'}, {'name': 'CQUAD4', 'id': '108', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '109', 'property': '1'}, {'name': 'CQUAD4', 'id': '110', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '111', 'property': '1'}, {'name': 'CQUAD4', 'id': '112', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '113', 'property': '1'}, {'name': 'CQUAD4', 'id': '116', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '119', 'property': '1'}, {'name': 'CQUAD4', 'id': '120', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '121', 'property': '1'}, {'name': 'CQUAD4', 'id': '122', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '123', 'property': '1'}, {'name': 'CQUAD4', 'id': '124', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '127', 'property': '1'}, {'name': 'CQUAD4', 'id': '130', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '131', 'property': '1'}, {'name': 'CQUAD4', 'id': '132', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '133', 'property': '1'}, {'name': 'CQUAD4', 'id': '134', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '135', 'property': '1'}, {'name': 'CQUAD4', 'id': '138', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '141', 'property': '1'}, {'name': 'CQUAD4', 'id': '142', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '143', 'property': '1'}, {'name': 'CQUAD4', 'id': '144', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '145', 'property': '1'}, {'name': 'CQUAD4', 'id': '146', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '149', 'property': '1'}, {'name': 'CQUAD4', 'id': '152', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '153', 'property': '1'}, {'name': 'CQUAD4', 'id': '154', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '155', 'property': '1'}, {'name': 'CQUAD4', 'id': '156', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '157', 'property': '1'}, {'name': 'CQUAD4', 'id': '160', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '163', 'property': '1'}, {'name': 'CQUAD4', 'id': '164', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '165', 'property': '1'}, {'name': 'CQUAD4', 'id': '166', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '167', 'property': '1'}, {'name': 'CQUAD4', 'id': '168', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '171', 'property': '1'}, {'name': 'CQUAD4', 'id': '174', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '175', 'property': '1'}, {'name': 'CQUAD4', 'id': '176', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '177', 'property': '1'}, {'name': 'CQUAD4', 'id': '178', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '179', 'property': '1'}, {'name': 'CQUAD4', 'id': '182', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '185', 'property': '1'}, {'name': 'CQUAD4', 'id': '186', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '187', 'property': '1'}, {'name': 'CQUAD4', 'id': '188', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '189', 'property': '1'}, {'name': 'CQUAD4', 'id': '190', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '193', 'property': '1'}, {'name': 'CQUAD4', 'id': '196', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '197', 'property': '1'}, {'name': 'CQUAD4', 'id': '198', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '199', 'property': '1'}, {'name': 'CQUAD4', 'id': '200', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '201', 'property': '1'}, {'name': 'CQUAD4', 'id': '204', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '207', 'property': '1'}, {'name': 'CQUAD4', 'id': '208', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '209', 'property': '1'}, {'name': 'CQUAD4', 'id': '210', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '211', 'property': '1'}, {'name': 'CQUAD4', 'id': '212', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '215', 'property': '1'}, {'name': 'CQUAD4', 'id': '218', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '219', 'property': '1'}, {'name': 'CQUAD4', 'id': '220', 'property': '1'},
                   {'name': 'CQUAD4', 'id': '221', 'property': '40'}, {'name': 'CQUAD4', 'id': '222', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '223', 'property': '40'}, {'name': 'CQUAD4', 'id': '226', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '229', 'property': '40'}, {'name': 'CQUAD4', 'id': '230', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '231', 'property': '40'}, {'name': 'CQUAD4', 'id': '232', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '233', 'property': '40'}, {'name': 'CQUAD4', 'id': '234', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '237', 'property': '40'}, {'name': 'CQUAD4', 'id': '240', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '241', 'property': '40'}, {'name': 'CQUAD4', 'id': '242', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '243', 'property': '40'}, {'name': 'CQUAD4', 'id': '244', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '245', 'property': '40'}, {'name': 'CQUAD4', 'id': '248', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '251', 'property': '40'}, {'name': 'CQUAD4', 'id': '252', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '253', 'property': '40'}, {'name': 'CQUAD4', 'id': '254', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '255', 'property': '40'}, {'name': 'CQUAD4', 'id': '256', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '259', 'property': '40'}, {'name': 'CQUAD4', 'id': '262', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '263', 'property': '40'}, {'name': 'CQUAD4', 'id': '264', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '265', 'property': '40'}, {'name': 'CQUAD4', 'id': '266', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '267', 'property': '40'}, {'name': 'CQUAD4', 'id': '270', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '273', 'property': '40'}, {'name': 'CQUAD4', 'id': '274', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '275', 'property': '40'}, {'name': 'CQUAD4', 'id': '276', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '277', 'property': '40'}, {'name': 'CQUAD4', 'id': '278', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '281', 'property': '40'}, {'name': 'CQUAD4', 'id': '284', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '285', 'property': '40'}, {'name': 'CQUAD4', 'id': '286', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '287', 'property': '40'}, {'name': 'CQUAD4', 'id': '288', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '289', 'property': '40'}, {'name': 'CQUAD4', 'id': '292', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '295', 'property': '40'}, {'name': 'CQUAD4', 'id': '296', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '297', 'property': '40'}, {'name': 'CQUAD4', 'id': '298', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '299', 'property': '40'}, {'name': 'CQUAD4', 'id': '300', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '303', 'property': '40'}, {'name': 'CQUAD4', 'id': '306', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '307', 'property': '40'}, {'name': 'CQUAD4', 'id': '308', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '309', 'property': '40'}, {'name': 'CQUAD4', 'id': '310', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '311', 'property': '40'}, {'name': 'CQUAD4', 'id': '314', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '317', 'property': '40'}, {'name': 'CQUAD4', 'id': '318', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '319', 'property': '40'}, {'name': 'CQUAD4', 'id': '320', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '321', 'property': '40'}, {'name': 'CQUAD4', 'id': '322', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '325', 'property': '40'}, {'name': 'CQUAD4', 'id': '328', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '329', 'property': '40'}, {'name': 'CQUAD4', 'id': '330', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '331', 'property': '40'}, {'name': 'CQUAD4', 'id': '332', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '333', 'property': '40'}, {'name': 'CQUAD4', 'id': '336', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '339', 'property': '40'}, {'name': 'CQUAD4', 'id': '340', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '341', 'property': '40'}, {'name': 'CQUAD4', 'id': '342', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '343', 'property': '40'}, {'name': 'CQUAD4', 'id': '344', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '347', 'property': '40'}, {'name': 'CQUAD4', 'id': '350', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '351', 'property': '40'}, {'name': 'CQUAD4', 'id': '352', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '353', 'property': '40'}, {'name': 'CQUAD4', 'id': '354', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '355', 'property': '40'}, {'name': 'CQUAD4', 'id': '358', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '361', 'property': '40'}, {'name': 'CQUAD4', 'id': '362', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '363', 'property': '40'}, {'name': 'CQUAD4', 'id': '364', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '365', 'property': '40'}, {'name': 'CQUAD4', 'id': '366', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '369', 'property': '40'}, {'name': 'CQUAD4', 'id': '372', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '373', 'property': '40'}, {'name': 'CQUAD4', 'id': '374', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '375', 'property': '40'}, {'name': 'CQUAD4', 'id': '376', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '377', 'property': '40'}, {'name': 'CQUAD4', 'id': '380', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '383', 'property': '40'}, {'name': 'CQUAD4', 'id': '384', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '385', 'property': '40'}, {'name': 'CQUAD4', 'id': '386', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '387', 'property': '40'}, {'name': 'CQUAD4', 'id': '388', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '391', 'property': '40'}, {'name': 'CQUAD4', 'id': '394', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '395', 'property': '40'}, {'name': 'CQUAD4', 'id': '396', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '397', 'property': '40'}, {'name': 'CQUAD4', 'id': '398', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '399', 'property': '40'}, {'name': 'CQUAD4', 'id': '402', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '405', 'property': '40'}, {'name': 'CQUAD4', 'id': '406', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '407', 'property': '40'}, {'name': 'CQUAD4', 'id': '408', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '409', 'property': '40'}, {'name': 'CQUAD4', 'id': '410', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '413', 'property': '40'}, {'name': 'CQUAD4', 'id': '416', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '417', 'property': '40'}, {'name': 'CQUAD4', 'id': '418', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '419', 'property': '40'}, {'name': 'CQUAD4', 'id': '420', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '421', 'property': '40'}, {'name': 'CQUAD4', 'id': '424', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '427', 'property': '40'}, {'name': 'CQUAD4', 'id': '428', 'property': '40'},
                   {'name': 'CQUAD4', 'id': '429', 'property': '40'}],
        'CTRIA3': [{'name': 'CTRIA3', 'id': '4', 'property': '1'}, {'name': 'CTRIA3', 'id': '5', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '7', 'property': '1'}, {'name': 'CTRIA3', 'id': '8', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '15', 'property': '1'}, {'name': 'CTRIA3', 'id': '16', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '18', 'property': '1'}, {'name': 'CTRIA3', 'id': '19', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '26', 'property': '1'}, {'name': 'CTRIA3', 'id': '27', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '29', 'property': '1'}, {'name': 'CTRIA3', 'id': '30', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '37', 'property': '1'}, {'name': 'CTRIA3', 'id': '38', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '40', 'property': '1'}, {'name': 'CTRIA3', 'id': '41', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '48', 'property': '1'}, {'name': 'CTRIA3', 'id': '49', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '51', 'property': '1'}, {'name': 'CTRIA3', 'id': '52', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '59', 'property': '1'}, {'name': 'CTRIA3', 'id': '60', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '62', 'property': '1'}, {'name': 'CTRIA3', 'id': '63', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '70', 'property': '1'}, {'name': 'CTRIA3', 'id': '71', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '73', 'property': '1'}, {'name': 'CTRIA3', 'id': '74', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '81', 'property': '1'}, {'name': 'CTRIA3', 'id': '82', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '84', 'property': '1'}, {'name': 'CTRIA3', 'id': '85', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '92', 'property': '1'}, {'name': 'CTRIA3', 'id': '93', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '95', 'property': '1'}, {'name': 'CTRIA3', 'id': '96', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '103', 'property': '1'}, {'name': 'CTRIA3', 'id': '104', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '106', 'property': '1'}, {'name': 'CTRIA3', 'id': '107', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '114', 'property': '1'}, {'name': 'CTRIA3', 'id': '115', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '117', 'property': '1'}, {'name': 'CTRIA3', 'id': '118', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '125', 'property': '1'}, {'name': 'CTRIA3', 'id': '126', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '128', 'property': '1'}, {'name': 'CTRIA3', 'id': '129', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '136', 'property': '1'}, {'name': 'CTRIA3', 'id': '137', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '139', 'property': '1'}, {'name': 'CTRIA3', 'id': '140', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '147', 'property': '1'}, {'name': 'CTRIA3', 'id': '148', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '150', 'property': '1'}, {'name': 'CTRIA3', 'id': '151', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '158', 'property': '1'}, {'name': 'CTRIA3', 'id': '159', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '161', 'property': '1'}, {'name': 'CTRIA3', 'id': '162', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '169', 'property': '1'}, {'name': 'CTRIA3', 'id': '170', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '172', 'property': '1'}, {'name': 'CTRIA3', 'id': '173', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '180', 'property': '1'}, {'name': 'CTRIA3', 'id': '181', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '183', 'property': '1'}, {'name': 'CTRIA3', 'id': '184', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '191', 'property': '1'}, {'name': 'CTRIA3', 'id': '192', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '194', 'property': '1'}, {'name': 'CTRIA3', 'id': '195', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '202', 'property': '1'}, {'name': 'CTRIA3', 'id': '203', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '205', 'property': '1'}, {'name': 'CTRIA3', 'id': '206', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '213', 'property': '1'}, {'name': 'CTRIA3', 'id': '214', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '216', 'property': '1'}, {'name': 'CTRIA3', 'id': '217', 'property': '1'},
                   {'name': 'CTRIA3', 'id': '224', 'property': '40'}, {'name': 'CTRIA3', 'id': '225', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '227', 'property': '40'}, {'name': 'CTRIA3', 'id': '228', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '235', 'property': '40'}, {'name': 'CTRIA3', 'id': '236', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '238', 'property': '40'}, {'name': 'CTRIA3', 'id': '239', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '246', 'property': '40'}, {'name': 'CTRIA3', 'id': '247', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '249', 'property': '40'}, {'name': 'CTRIA3', 'id': '250', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '257', 'property': '40'}, {'name': 'CTRIA3', 'id': '258', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '260', 'property': '40'}, {'name': 'CTRIA3', 'id': '261', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '268', 'property': '40'}, {'name': 'CTRIA3', 'id': '269', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '271', 'property': '40'}, {'name': 'CTRIA3', 'id': '272', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '279', 'property': '40'}, {'name': 'CTRIA3', 'id': '280', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '282', 'property': '40'}, {'name': 'CTRIA3', 'id': '283', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '290', 'property': '40'}, {'name': 'CTRIA3', 'id': '291', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '293', 'property': '40'}, {'name': 'CTRIA3', 'id': '294', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '301', 'property': '40'}, {'name': 'CTRIA3', 'id': '302', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '304', 'property': '40'}, {'name': 'CTRIA3', 'id': '305', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '312', 'property': '40'}, {'name': 'CTRIA3', 'id': '313', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '315', 'property': '40'}, {'name': 'CTRIA3', 'id': '316', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '323', 'property': '40'}, {'name': 'CTRIA3', 'id': '324', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '326', 'property': '40'}, {'name': 'CTRIA3', 'id': '327', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '334', 'property': '40'}, {'name': 'CTRIA3', 'id': '335', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '337', 'property': '40'}, {'name': 'CTRIA3', 'id': '338', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '345', 'property': '40'}, {'name': 'CTRIA3', 'id': '346', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '348', 'property': '40'}, {'name': 'CTRIA3', 'id': '349', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '356', 'property': '40'}, {'name': 'CTRIA3', 'id': '357', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '359', 'property': '40'}, {'name': 'CTRIA3', 'id': '360', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '367', 'property': '40'}, {'name': 'CTRIA3', 'id': '368', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '370', 'property': '40'}, {'name': 'CTRIA3', 'id': '371', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '378', 'property': '40'}, {'name': 'CTRIA3', 'id': '379', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '381', 'property': '40'}, {'name': 'CTRIA3', 'id': '382', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '389', 'property': '40'}, {'name': 'CTRIA3', 'id': '390', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '392', 'property': '40'}, {'name': 'CTRIA3', 'id': '393', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '400', 'property': '40'}, {'name': 'CTRIA3', 'id': '401', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '403', 'property': '40'}, {'name': 'CTRIA3', 'id': '404', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '411', 'property': '40'}, {'name': 'CTRIA3', 'id': '412', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '414', 'property': '40'}, {'name': 'CTRIA3', 'id': '415', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '422', 'property': '40'}, {'name': 'CTRIA3', 'id': '423', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '425', 'property': '40'},
                   {'name': 'CTRIA3', 'id': '426', 'property': '40'}],
        'CBEAM': [{'name': 'CBEAM', 'id': '430', 'property': '20'}, {'name': 'CBEAM', 'id': '431', 'property': '20'},
                  {'name': 'CBEAM', 'id': '432', 'property': '20'}, {'name': 'CBEAM', 'id': '433', 'property': '20'},
                  {'name': 'CBEAM', 'id': '434', 'property': '20'}, {'name': 'CBEAM', 'id': '435', 'property': '20'},
                  {'name': 'CBEAM', 'id': '436', 'property': '20'}, {'name': 'CBEAM', 'id': '437', 'property': '20'},
                  {'name': 'CBEAM', 'id': '438', 'property': '20'}, {'name': 'CBEAM', 'id': '439', 'property': '20'},
                  {'name': 'CBEAM', 'id': '440', 'property': '20'}, {'name': 'CBEAM', 'id': '441', 'property': '20'},
                  {'name': 'CBEAM', 'id': '442', 'property': '20'}, {'name': 'CBEAM', 'id': '443', 'property': '20'},
                  {'name': 'CBEAM', 'id': '444', 'property': '20'}, {'name': 'CBEAM', 'id': '445', 'property': '20'},
                  {'name': 'CBEAM', 'id': '446', 'property': '20'}, {'name': 'CBEAM', 'id': '447', 'property': '20'},
                  {'name': 'CBEAM', 'id': '448', 'property': '20'}, {'name': 'CBEAM', 'id': '449', 'property': '20'},
                  {'name': 'CBEAM', 'id': '450', 'property': '20'}, {'name': 'CBEAM', 'id': '451', 'property': '20'},
                  {'name': 'CBEAM', 'id': '452', 'property': '20'}, {'name': 'CBEAM', 'id': '453', 'property': '20'},
                  {'name': 'CBEAM', 'id': '454', 'property': '20'}, {'name': 'CBEAM', 'id': '455', 'property': '20'},
                  {'name': 'CBEAM', 'id': '456', 'property': '20'}, {'name': 'CBEAM', 'id': '457', 'property': '20'},
                  {'name': 'CBEAM', 'id': '458', 'property': '20'}, {'name': 'CBEAM', 'id': '459', 'property': '20'},
                  {'name': 'CBEAM', 'id': '460', 'property': '20'}, {'name': 'CBEAM', 'id': '461', 'property': '20'},
                  {'name': 'CBEAM', 'id': '462', 'property': '20'}, {'name': 'CBEAM', 'id': '463', 'property': '20'},
                  {'name': 'CBEAM', 'id': '464', 'property': '20'}, {'name': 'CBEAM', 'id': '465', 'property': '20'},
                  {'name': 'CBEAM', 'id': '466', 'property': '20'}, {'name': 'CBEAM', 'id': '467', 'property': '20'},
                  {'name': 'CBEAM', 'id': '468', 'property': '20'}],
        'CBAR': [{'name': 'CBAR', 'id': '469', 'property': '30'}, {'name': 'CBAR', 'id': '470', 'property': '30'},
                 {'name': 'CBAR', 'id': '471', 'property': '30'}, {'name': 'CBAR', 'id': '472', 'property': '30'},
                 {'name': 'CBAR', 'id': '473', 'property': '30'}, {'name': 'CBAR', 'id': '474', 'property': '30'},
                 {'name': 'CBAR', 'id': '475', 'property': '30'}, {'name': 'CBAR', 'id': '476', 'property': '30'},
                 {'name': 'CBAR', 'id': '477', 'property': '30'}, {'name': 'CBAR', 'id': '478', 'property': '30'},
                 {'name': 'CBAR', 'id': '479', 'property': '30'}, {'name': 'CBAR', 'id': '480', 'property': '30'},
                 {'name': 'CBAR', 'id': '481', 'property': '30'}, {'name': 'CBAR', 'id': '482', 'property': '30'},
                 {'name': 'CBAR', 'id': '483', 'property': '30'}, {'name': 'CBAR', 'id': '484', 'property': '30'},
                 {'name': 'CBAR', 'id': '485', 'property': '30'}, {'name': 'CBAR', 'id': '486', 'property': '30'},
                 {'name': 'CBAR', 'id': '487', 'property': '30'}, {'name': 'CBAR', 'id': '488', 'property': '30'},
                 {'name': 'CBAR', 'id': '489', 'property': '30'}, {'name': 'CBAR', 'id': '490', 'property': '30'},
                 {'name': 'CBAR', 'id': '491', 'property': '30'}, {'name': 'CBAR', 'id': '492', 'property': '30'},
                 {'name': 'CBAR', 'id': '493', 'property': '30'}, {'name': 'CBAR', 'id': '494', 'property': '30'},
                 {'name': 'CBAR', 'id': '495', 'property': '30'}, {'name': 'CBAR', 'id': '496', 'property': '30'},
                 {'name': 'CBAR', 'id': '497', 'property': '30'}, {'name': 'CBAR', 'id': '498', 'property': '30'},
                 {'name': 'CBAR', 'id': '499', 'property': '30'}, {'name': 'CBAR', 'id': '500', 'property': '30'},
                 {'name': 'CBAR', 'id': '501', 'property': '30'}, {'name': 'CBAR', 'id': '502', 'property': '30'},
                 {'name': 'CBAR', 'id': '503', 'property': '30'}, {'name': 'CBAR', 'id': '504', 'property': '30'},
                 {'name': 'CBAR', 'id': '505', 'property': '30'}, {'name': 'CBAR', 'id': '506', 'property': '30'},
                 {'name': 'CBAR', 'id': '507', 'property': '30'}],
        'PSHELL': [{'name': 'PSHELL', 'id': '1', 'property': '1'}],
        'PBEAM': [{'name': 'PBEAM', 'id': '20', 'property': '1'}],
        'PBAR': [{'name': 'PBAR', 'id': '30', 'property': '1'}],
        'PCOMP': [{'name': 'PCOMP', 'id': '40', 'property': '-1.47200'}],
        'MAT1': [{'name': 'MAT1', 'id': '1', 'property': '71700.0'}],
        'MAT8': [{'name': 'MAT8', 'id': '2', 'property': '154000.0'}]}

    return JsonResponse(card_json)
