from django.shortcuts import render, redirect
from django.http import JsonResponse


# Create your views here.

def card_view(request):
    # card = models.Card()
    # card.name = "CQUAD4"
    # card.id = 12
    # card.count = 987
    card_json = {'CQUAD4': [{'name': 'CQUAD4', 'id': '1', 'property': '1'}, {'name': 'CQUAD4', 'id': '2', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '3', 'property': '1'}, {'name': 'CQUAD4', 'id': '6', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '9', 'property': '1'}, {'name': 'CQUAD4', 'id': '10', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '11', 'property': '1'}, {'name': 'CQUAD4', 'id': '12', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '13', 'property': '1'}, {'name': 'CQUAD4', 'id': '14', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '17', 'property': '1'}, {'name': 'CQUAD4', 'id': '20', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '21', 'property': '1'}, {'name': 'CQUAD4', 'id': '22', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '23', 'property': '1'}, {'name': 'CQUAD4', 'id': '24', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '25', 'property': '1'}, {'name': 'CQUAD4', 'id': '28', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '31', 'property': '1'}, {'name': 'CQUAD4', 'id': '32', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '33', 'property': '1'}, {'name': 'CQUAD4', 'id': '34', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '35', 'property': '1'}, {'name': 'CQUAD4', 'id': '36', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '39', 'property': '1'}, {'name': 'CQUAD4', 'id': '42', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '43', 'property': '1'}, {'name': 'CQUAD4', 'id': '44', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '45', 'property': '1'}, {'name': 'CQUAD4', 'id': '46', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '47', 'property': '1'}, {'name': 'CQUAD4', 'id': '50', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '53', 'property': '1'}, {'name': 'CQUAD4', 'id': '54', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '55', 'property': '1'}, {'name': 'CQUAD4', 'id': '56', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '57', 'property': '1'}, {'name': 'CQUAD4', 'id': '58', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '61', 'property': '1'}, {'name': 'CQUAD4', 'id': '64', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '65', 'property': '1'}, {'name': 'CQUAD4', 'id': '66', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '67', 'property': '1'}, {'name': 'CQUAD4', 'id': '68', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '69', 'property': '1'}, {'name': 'CQUAD4', 'id': '72', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '75', 'property': '1'}, {'name': 'CQUAD4', 'id': '76', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '77', 'property': '1'}, {'name': 'CQUAD4', 'id': '78', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '79', 'property': '1'}, {'name': 'CQUAD4', 'id': '80', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '83', 'property': '1'}, {'name': 'CQUAD4', 'id': '86', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '87', 'property': '1'}, {'name': 'CQUAD4', 'id': '88', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '89', 'property': '1'}, {'name': 'CQUAD4', 'id': '90', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '91', 'property': '1'}, {'name': 'CQUAD4', 'id': '94', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '97', 'property': '1'}, {'name': 'CQUAD4', 'id': '98', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '99', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '100', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '101', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '102', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '105', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '108', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '109', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '110', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '111', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '112', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '113', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '116', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '119', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '120', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '121', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '122', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '123', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '124', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '127', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '130', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '131', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '132', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '133', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '134', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '135', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '138', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '141', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '142', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '143', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '144', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '145', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '146', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '149', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '152', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '153', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '154', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '155', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '156', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '157', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '160', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '163', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '164', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '165', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '166', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '167', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '168', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '171', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '174', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '175', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '176', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '177', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '178', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '179', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '182', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '185', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '186', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '187', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '188', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '189', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '190', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '193', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '196', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '197', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '198', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '199', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '200', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '201', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '204', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '207', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '208', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '209', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '210', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '211', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '212', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '215', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '218', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '219', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '220', 'property': '1'},
                       {'name': 'CQUAD4', 'id': '221', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '222', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '223', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '226', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '229', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '230', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '231', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '232', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '233', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '234', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '237', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '240', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '241', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '242', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '243', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '244', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '245', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '248', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '251', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '252', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '253', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '254', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '255', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '256', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '259', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '262', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '263', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '264', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '265', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '266', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '267', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '270', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '273', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '274', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '275', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '276', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '277', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '278', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '281', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '284', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '285', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '286', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '287', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '288', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '289', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '292', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '295', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '296', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '297', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '298', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '299', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '300', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '303', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '306', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '307', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '308', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '309', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '310', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '311', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '314', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '317', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '318', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '319', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '320', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '321', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '322', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '325', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '328', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '329', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '330', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '331', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '332', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '333', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '336', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '339', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '340', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '341', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '342', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '343', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '344', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '347', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '350', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '351', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '352', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '353', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '354', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '355', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '358', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '361', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '362', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '363', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '364', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '365', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '366', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '369', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '372', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '373', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '374', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '375', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '376', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '377', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '380', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '383', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '384', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '385', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '386', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '387', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '388', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '391', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '394', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '395', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '396', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '397', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '398', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '399', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '402', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '405', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '406', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '407', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '408', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '409', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '410', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '413', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '416', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '417', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '418', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '419', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '420', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '421', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '424', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '427', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '428', 'property': '40'},
                       {'name': 'CQUAD4', 'id': '429', 'property': '40'}]}

    return JsonResponse(card_json)
